// renderer.js
const td=document.getElementById("time-display");
const ib=document.getElementById("info-bar");
const di=document.getElementById("date-inline");
const ti=document.getElementById("tz-inline");
const cl=document.getElementById("clock");
let cfg={},cts="",cds="",ti2=null,rdt=null,df=null,ltk="";
function gdf(l){try{return new Intl.DateTimeFormat(l==="zh"?"zh-CN":"en-US",{year:"numeric",month:"2-digit",day:"2-digit"});}catch(e){return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit"});}}
function fmt(d){if(!df)return"";const p=df.formatToParts(d),m={};p.forEach(x=>m[x.type]=x.value);return cfg.language==="zh"?m.year+"年"+m.month+"月"+m.day+"日":["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][parseInt(m.month,10)-1]+" "+m.day+", "+m.year;}
function ga(){if(!cfg.autoColor)return null;const h=new Date().getHours();return h>=6&&h<18?"#000000":"#ffffff";}
function gz(d,o){const u=d.getUTCHours(),m=d.getUTCMinutes();return String((u+o+24)%24).padStart(2,"0")+":"+String(m).padStart(2,"0");}
function ri(now){if(cfg.showDate!==false){const s=fmt(now);if(s!==cds){di.textContent=s;cds=s;}di.style.display="";}else di.style.display="none";const tz=(cfg.extraTimezones||[]).slice(0,2);if(tz.length){let k="";for(let j=0;j<tz.length;j++)k+=tz[j].label+","+tz[j].offset+","+gz(now,tz[j].offset)+"|";if(k!==ltk){ltk=k;ti.innerHTML="";for(let j=0;j<tz.length;j++){const e=document.createElement("span");e.style.marginLeft="8px";e.textContent=tz[j].label+" "+gz(now,tz[j].offset);ti.appendChild(e);}}ti.style.display="";}else ti.style.display="none";ib.style.display=cfg.showDate!==false||tz.length?"":"none";}
function gd(){const n=new Date();const hh=String(n.getHours()).padStart(2,"0");const mm=String(n.getMinutes()).padStart(2,"0");const ss=String(n.getSeconds()).padStart(2,"0");return cfg.showSeconds!==false?{d:(hh+mm+ss).split(""),cc:2}:{d:(hh+mm).split(""),cc:1};}
function bd(dg,cc){td.innerHTML="";let ci=0;for(let i=0;i<dg.length;i++){if(i>0&&i%2===0&&ci<cc){const e=document.createElement("span");e.className="colon";e.textContent=":";td.appendChild(e);ci++;}const g=document.createElement("span");g.className="digit-group";const c=document.createElement("span");c.className="digit-current";c.textContent=dg[i];g.appendChild(c);const n=document.createElement("span");n.className="digit-next";n.textContent=dg[i];g.appendChild(n);td.appendChild(g);}}
function rs(c,n){c.style.transition=n.style.transition="none";c.classList.remove("animate-out");n.classList.remove("animate-in");c.style.transform=c.style.opacity=n.style.transform=n.style.opacity="";void c.offsetHeight;c.style.transition=n.style.transition="";}
function uc(){const{ d: nd, cc }=gd();const nts=nd.join("");ri(new Date());const ac=ga();if(ac){td.style.color=ac;ib.style.color=ac;}if(!cts||cts.length!==nd.length){bd(nd,cc);cts=nts;return;}for(let i=0;i<nd.length;i++){const g=td.querySelectorAll(".digit-group")[i];if(!g)continue;const ce=g.querySelector(".digit-current"),ne=g.querySelector(".digit-next");if(!ce||!ne||ce.textContent===nd[i])continue;rs(ce,ne);ne.textContent=nd[i];ce.classList.add("animate-out");ne.classList.add("animate-in");const _ce=ce,_ne=ne,_d=nd[i];setTimeout(()=>{_ce.textContent=_d;rs(_ce,_ne);},(cfg.animDuration||350)+30);}cts=nts;}
function sc(){if(ti2)clearInterval(ti2);uc();ti2=setInterval(uc,1000);}function stc(){if(ti2){clearInterval(ti2);ti2=null;}}
function acf(){const ec=ga()||cfg.color;const bg=cfg.bgColor&&cfg.bgColor.startsWith("rgba")?cfg.bgColor:"transparent";const ad=(cfg.animDuration||350);td.style.color=ec;td.style.backgroundColor=bg;td.style.fontFamily=cfg.fontFamily;td.style.fontSize=(cfg.fontSize||200)+"px";const sz=Math.round((cfg.fontSize||200)*0.3);ib.style.fontFamily=cfg.fontFamily;ib.style.fontSize=sz+"px";ib.style.color=ec;ib.style.backgroundColor=bg;cl.style.setProperty("--anim-duration",ad+"ms");cl.classList.toggle("date-above",cfg.datePosition==="above");}
function sp(v){window.electronAPI.setPassthrough(!!v);}
function fw(){const r=td.getBoundingClientRect();const b=ib.getBoundingClientRect();let w=r.width,h=r.height;if(b.width>w)w=b.width;if(ib.style.display!=="none"&&b.height>0)h+=b.height+4;if(w>0&&h>0)window.electronAPI.resizeWindow({width:w,height:h});}
async function init(){try{cfg=await window.electronAPI.getConfig();}catch(e){cfg={};}if(!cfg.color)cfg.color="#ffffff";if(!cfg.bgColor)cfg.bgColor="rgba(0,0,0,0)";if(!cfg.fontFamily)cfg.fontFamily="Arial";if(!cfg.fontSize)cfg.fontSize=200;if(cfg.showSeconds===undefined)cfg.showSeconds=true;if(cfg.showDate===undefined)cfg.showDate=true;if(!cfg.datePosition)cfg.datePosition="below";if(!cfg.language)cfg.language="zh";if(cfg.autoColor===undefined)cfg.autoColor=false;if(!cfg.extraTimezones)cfg.extraTimezones=[];df=gdf(cfg.language);acf();if(cfg.passthrough)sp(true);sc();function ft(){requestAnimationFrame(()=>requestAnimationFrame(fw));}ft();setTimeout(ft,300);window.electronAPI.onConfigUpdated(nc=>{const lc=nc.language&&nc.language!==cfg.language;Object.assign(cfg,nc);if(lc)df=gdf(cfg.language);if(nc.passthrough!==undefined)sp(!!nc.passthrough);acf();cds="";ltk="";if(nc.showSeconds!==undefined||lc||nc.extraTimezones!==undefined)cts="";uc();if(nc.fontSize!==undefined||nc.showSeconds!==undefined||nc.fontFamily!==undefined||nc.showDate!==undefined||nc.datePosition!==undefined||lc||nc.autoColor!==undefined||nc.extraTimezones!==undefined){if(rdt)clearTimeout(rdt);rdt=setTimeout(()=>{rdt=null;requestAnimationFrame(()=>requestAnimationFrame(fw));},300);}});window.addEventListener("beforeunload",()=>{stc();if(rdt)clearTimeout(rdt);});}init();
